targets:
  - name: staging
    args:
      environment: staging
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: devops-directive-kubernetes-course

  - name: production
    args:
      environment: production
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_k8s-tutorial-project-445008_us-central1-a_fardil-kubernetes-course-cluster

args:
  - name: environment

discriminator: kluctl-{{ target.name }}
